apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-app
  namespace: dev-environment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payroll
  template:
    metadata:
      labels:
        app: payroll
    spec:
  containers:
  - name: payroll-container
    image: sanket1718/payroll-app:17
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: tmp-volume
      mountPath: /tmp
    - name: run-volume
      mountPath: /run  # This solves the /run/nginx.pid error!
  volumes:
  - name: tmp-volume
    emptyDir: {}
  - name: run-volume
    emptyDir: {}
